universe = vanilla

container_image = /home/ehuffaker/staging/tidyverse.sif

executable = run_simulation.sh
arguments = $(rho) $(sample_size)

transfer_input_files = simulation2.R

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_output_files = simulation_summary_r$(rho)_n$(sample_size).csv

output = logs/simulation_r$(rho)_n$(sample_size).out
error = logs/simulation_r$(rho)_n$(sample_size).err
log = logs/simulation_r$(rho)_n$(sample_size).log

request_cpus = 1
request_memory = 2GB
request_disk = 4GB

queue rho, sample_size from (
0.15 20
0.15 40
0.15 60
0.25 20
0.25 40
0.25 60
0.35 20
0.35 40
0.35 60
)

